### PR TITLE
More Usability, Better Stability, Clearer Errors

### LINKED ISSUE #9: Error Message Accessibility
We need to catch all possible errors and turn them into something actionable for the end-user, even when the only thing to do is "refresh the browser" or "file a support request".

- [x] bring esptool files local and update the stubs

- [x] establish a top-level error handler that gives generic instructions to:
  - try to `Connect` again
  - then refreshing the browser and try to `Connect`
  - then filing a support ticket with the copied error message

- [x] doublecheck that the drop-down selected board matches the WebSerial selected board via `espTool.chipType()`

- [ ] ESP32-V2 connection issues:
  - "Couldn't sync to ESP. Try resetting." could be better worded, explain how to reset, etc
  - "A buffer overrun has been detected." sometimes comes with it and breaks the `connect` button

- [ ] chase down and improve as many error messages as we can find:
  - [ ] 27 `throw` statements between esptool and the firmware script
  - [ ] 19 mentions of `DOMException` in the [web serial spec](https://wicg.github.io/serial/)
  - [ ] "The device has been lost." got this when trying to flash the wrong board, maybe it will never happen with matching boards? keep an eye out
  - [ ] `espTool.sync()` would also halt and not message anything sometimes, when flashing the wrong board. keep an eye out

### PR DESCRIPTION
**Pull request by lorennorman**
closes #9

### CODE REVIEW

File: js/esptool.js [hunk 1]
```diff
@@ -717,7 +729,7 @@ class EspLoader {
    */
   async sync() {
     this.logMsg("Performing sync...")
-    for (let i = 0; i < 8; i++) {
+    for (let i = 0; i < 5; i++) {
```
Comment (makermelissa) [inline js/esptool.js:732]: Is there a reason you reduced this? This was at 8 attempts because that's what the official esptool does.

File: js/script.js [hunk 2]
```diff
@@ -4,12 +4,25 @@
...
 
 const FIRMWARE_API = "//io.adafruit.com"
+const QUICK_START_LINK = "https://learn.adafruit.com/quickstart-adafruit-io-wippersnapper/installing-wippersnapper"
 const DO_DOWNLOAD = false
 
+const BOARD_TO_CHIP_MAP = {
+  'feather-esp8266': ESP8266,
+  'feather-esp32': ESP32,
+  'feather-esp32-v2-daily': ESP32
+}
```
Comment (makermelissa) [inline js/script.js:14]: Would this make more sense to just use the value in the board definition such as https://github.com/adafruit/Wippersnapper_Boards/blob/main/boards/feather-esp32-v2-daily/definition.json#L3?

File: js/script.js [hunk 3]
```diff
@@ -424,11 +472,23 @@ function debugMsg(...args) {
     }
 }
 
-function errorMsg(text) {
+function errorMsg(text, forwardLink=null) {
+    // regular log with red Error: prefix
     logMsg('<span class="error-message">Error:</span> ' + text);
-    console.error(text);
```
Comment (makermelissa) [inline js/script.js:429]: One of the reasons for using console.error() was to help trace where the error initially occurred. Perhaps make it so it only happens if debugging?

**Review by makermelissa — CHANGES_REQUESTED** [review]
I added a few comments. Also, keep in mind when we start using the NPM version of esptool, the changes to esptool.js will be reverted unless updated in https://github.com/NabuCasa/esp-web-flasher.

File: js/esptool.js (hunk 1 above)
Comment (lorennorman) [reply js/esptool.js:732]: I believe this was me putting it back how it was, I think I had bumped it to 8 while I was testing various things and accidentally committed it.

See here:
https://github.com/adafruit/Adafruit_WebSerial_ESPTool/blob/main/js/esptool.js#L720

I trust you to tell me what it should actually be.

File: js/script.js (hunk 2 above)
Comment (lorennorman) [reply js/script.js:14]: I think you are proposing it would look like:
```javascript
const BOARD_TO_CHIP_MAP = {
  'esp8266': ESP8266,
  'ESP32': ESP32,
}
```
...and the call-site would change from:
```javascript
(BOARD_TO_CHIP_MAP[firmware.id] == chipType)
```
...to...
```javascript
(BOARD_TO_CHIP_MAP[firmware.mcuName] == chipType)
```
Am I getting that right?

🤔 

This would:
- require me to expose that value from the API (not hard)
- allow this map to grow more easily (scales better if LOTS of boards get added)
- need to ensure they're matchable, already see case sensitivity between 8266 and 32

I'm kinda "meh" on this, what do you think? Did I miss something important in this analysis?

File: js/esptool.js (hunk 1 above)
Comment (makermelissa) [reply js/esptool.js:732]: Oh gotcha, I was thinking of https://github.com/adafruit/Adafruit_WebSerial_ESPTool/blob/main/js/esptool.js#L743

File: js/script.js (hunk 2 above)
Comment (makermelissa) [reply js/script.js:14]: If you think this would be harder to maintain, we can leave it as is. My thoughts were more along the lines, we just define the chip type in the boards definition to make adding new boards easier.

File: js/script.js (hunk 3 above)
Comment (lorennorman) [reply js/script.js:429]: Yep I agree, it's super important and helpful! It's still happening on the next few lines:
```javascript
    // strip html for console and alerts
    const strippedText = text.replaceAll(/<.*?>/g, "")
    // all errors go to the browser dev console
    console.error(strippedText);
```

I used HTML in some of my errors to make them read better since we were improving the UX for lay persons, but of course that only looks good for the in-document stuff, just noise for console and alerts.

Comment (makermelissa) [reply js/script.js:429]: Ah, ok. Fair enough then.

File: js/script.js (hunk 2 above)
Comment (makermelissa) [reply js/script.js:14]: Another thought on this regarding case sensitivity is to just take whatever in the board definition and make it lowercase before looking it up.

Comment (lorennorman) [reply js/script.js:14]: Cool makes sense. I'll leave it for now since everything works and I'm ready to go over to IO and start pulling things that direction. Once it is being served and populated from IO directly this kind of change is TRIVIAL.

**Review by makermelissa — APPROVED** [review]
